### ISSUE TITLE
How to download the pretrained weights?

### ISSUE THREAD

**Issue by jinfagang** [taehoonlee/tensornets#31]
I wanna test yolo2 or yolov3 combined with mobilenetv2, as following codes, how to download the models?

```
import tensorflow as tf
import tensornets as nets

inputs = tf.placeholder(tf.float32, [None, 416, 416, 3])
model = nets.YOLOv2(inputs, nets.mobilenets.MobileNet75v2)

img = nets.utils.load_img('cat.jpg')

with tf.Session() as sess:
    sess.run(model.pretrained())

    preds = sess.run(model, {inputs: model.preprocess(img)})
    boxes = model.get_boxes(preds, img.shape[1:3])

    print(boxes)
```

**Comment by taehoonlee** [comment]
Thank you for trying TensorNets, @jinfagang. There are no pre-trained weights for yolo with mobilenetv2. In order to train them, [this example](https://github.com/taehoonlee/tensornets/blob/master/examples/train_yolov2.py) would be helpful. The point is to exploit the pre-trained weights only for the stem layers as follows:
```
sess.run(tf.global_variables_initializer())
sess.run(model.stem.pretrained())
```

**Comment by taehoonlee** [comment]
@jinfagang, I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.
