### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by Baakchsu** [taehoonlee/tensornets#53]
Since tensorflow.contrib methods were moved to tensorflow.core, I'm not able to run tensornets code for YOLOv3COCO.

**Comment by sarathak** [comment]
i think not supporting tensorflow 2

**Comment by meysamsadeghi** [comment]
I am using TF 2, and have the same error. Is there any workaround? Or do you have any plan for addressing this?
@taehoonlee

**Comment by taehoonlee** [comment]
Thank you for using TensorNets, @Baakchsu, @sarathak, @meysamsadeghi. Yes, I'm going to address this issue. I would appreciate it if you can be patient on the problem.

**Comment by cozy-chestnut** [comment]
> 
> 
> Thank you for using TensorNets, @Baakchsu, @sarathak, @meysamsadeghi. Yes, I'm going to address this issue. I would appreciate it if you can be patient on the problem.

Thanks for addressing this issue. I'm waiting for a solution to this as well. Again, thanks for providing this handy tool to us. =]

**Comment by taehoonlee** [comment]
Thank you for being patient, @Baakchsu, @sarathak, @meysamsadeghi, @cozy-chestnut. The PR #55 adds TF 2 supports, so I'll close the issue for now. But I am not sure if it will work perfectly in your codes because this is one of the temporal solutions. Please let me know by opening another issue if you have additional comments.
